---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-goof
  name: java-goof
  namespace: java-goof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-goof
  template:
    metadata:
      labels:
        app: java-goof
    spec:
      containers:
      - image: northamerica-northeast2-docker.pkg.dev/snyk-cx-se-demo/sperciballi-registry/java-goof:gke
        imagePullPolicy: Always
        name: java-goof
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-goof
  name: java-goof
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-goof
